
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this
 * license Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.ArrayList;


/**
 *
 * @author kprzyby
 */
public class Magazyn extends javax.swing.JFrame {

	ArrayList<Towar> towary = new ArrayList<Towar>();
	int wybranyTowarIndeks = -1;

	/**
	 * Creates new form Magazyn
	 */
	public Magazyn() {
		initComponents();

		// dane testowe
		towary.add(new Towar("Koszula", 12));
		towary.add(new Towar("Spodnie", 100));
		towary.add(new Towar("Rower", 1200));


		if (!towary.isEmpty()) {

			wybranyTowarIndeks = 0;

			// ustaw etykietę licznikową
			licznikLabel.setText((wybranyTowarIndeks + 1) + "/" + towary.size());
			nazwaTextField.setText(towary.get(wybranyTowarIndeks).getNazwa());
			nazwaTextField.setText("" + towary.get(wybranyTowarIndeks).getCena());
		} else
			licznikLabel.setText("Brak produktów");
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		nowyDialog = new javax.swing.JDialog();
		jLabel2 = new javax.swing.JLabel();
		nowyLicznikLabel = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		nowaNazwaTextField = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		nowaCenaTextField = new javax.swing.JTextField();
		zapiszButton = new javax.swing.JButton();
		anulujButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		licznikLabel = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		nazwaTextField = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		cenaTextField = new javax.swing.JTextField();
		dodajButton = new javax.swing.JButton();
		usunButton = new javax.swing.JButton();
		nastepnyButton = new javax.swing.JButton();
		poprzedniButton = new javax.swing.JButton();
		zamknijButton = new javax.swing.JButton();

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
		jLabel2.setText("MAGAZYN");

		nowyLicznikLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
		nowyLicznikLabel.setText("Brak produktów");

		jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		jLabel5.setText("Nazwa towaru:");

		nowaNazwaTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

		jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		jLabel6.setText("Cena towaru:");

		nowaCenaTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

		zapiszButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		zapiszButton.setText("Zapisz");
		zapiszButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				zapiszButtonActionPerformed(evt);
			}
		});

		anulujButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		anulujButton.setText("Anuluj");
		anulujButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				anulujButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout nowyDialogLayout =
				new javax.swing.GroupLayout(nowyDialog.getContentPane());
		nowyDialog.getContentPane().setLayout(nowyDialogLayout);
		nowyDialogLayout.setHorizontalGroup(nowyDialogLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						nowyDialogLayout.createSequentialGroup().addGroup(nowyDialogLayout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(nowyDialogLayout.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(zapiszButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												202,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(anulujButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												230,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(nowyDialogLayout.createSequentialGroup()
										.addGap(87, 87, 87)
										.addGroup(nowyDialogLayout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(nowyDialogLayout
														.createSequentialGroup()
														.addGroup(nowyDialogLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		jLabel5)
																.addComponent(
																		jLabel6))
														.addGap(56, 56, 56)
														.addGroup(nowyDialogLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		nowaCenaTextField)
																.addComponent(
																		nowaNazwaTextField)))
												.addGroup(nowyDialogLayout
														.createSequentialGroup()
														.addComponent(jLabel2)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																316,
																Short.MAX_VALUE)
														.addComponent(
																nowyLicznikLabel)))))
								.addGap(44, 44, 44)));
		nowyDialogLayout.setVerticalGroup(nowyDialogLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(nowyDialogLayout.createSequentialGroup().addGap(72, 72, 72)
						.addGroup(nowyDialogLayout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(nowyLicznikLabel))
						.addGap(59, 59, 59)
						.addGroup(nowyDialogLayout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(nowaNazwaTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(26, 26, 26)
						.addGroup(nowyDialogLayout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel6).addComponent(nowaCenaTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(76, 76, 76)
						.addGroup(nowyDialogLayout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(zapiszButton).addComponent(anulujButton))
						.addContainerGap(51, Short.MAX_VALUE)));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Zarządzanie towarami");

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
		jLabel1.setText("MAGAZYN");

		licznikLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
		licznikLabel.setText("Brak produktów");

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		jLabel3.setText("Nazwa towaru:");

		nazwaTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

		jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		jLabel4.setText("Cena towaru:");

		cenaTextField.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

		dodajButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		dodajButton.setText("Dodaj");
		dodajButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dodajButtonActionPerformed(evt);
			}
		});

		usunButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		usunButton.setText("Usuń");

		nastepnyButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		nastepnyButton.setText("Następny");

		poprzedniButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		poprzedniButton.setText("Poprzedni");

		zamknijButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
		zamknijButton.setText("Zamknij");
		zamknijButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				zamknijButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(115, 115, 115).addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(dodajButton,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(nastepnyButton,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												216, Short.MAX_VALUE))
								.addGap(46, 46, 46)
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(poprzedniButton,
												javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												230,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(usunButton,
												javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												230,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(394, 394, 394).addComponent(zamknijButton,
										javax.swing.GroupLayout.PREFERRED_SIZE, 230,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
								.createSequentialGroup().addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(licznikLabel))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
								.createSequentialGroup()
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel3).addComponent(jLabel4))
								.addGap(56, 56, 56)
								.addGroup(layout.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(cenaTextField)
										.addComponent(nazwaTextField))))
						.addGap(92, 92, 92)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(100, 100, 100).addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(licznikLabel))
						.addGap(103, 103, 103)
						.addGroup(layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(nazwaTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(26, 26, 26)
						.addGroup(layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(cenaTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(110, 110, 110)
						.addGroup(layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(dodajButton).addComponent(usunButton))
						.addGap(18, 18, 18)
						.addGroup(layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(nastepnyButton).addComponent(poprzedniButton)
								.addComponent(zamknijButton))
						.addContainerGap(59, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void zamknijButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_zamknijButtonActionPerformed
		// TODO add your handling code here:
		dispose();
	}// GEN-LAST:event_zamknijButtonActionPerformed

	private void dodajButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dodajButtonActionPerformed
		// TODO add your handling code here:
		nowyDialog.pack();
		nowyDialog.setVisible(true);
	}// GEN-LAST:event_dodajButtonActionPerformed

	private void anulujButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_anulujButtonActionPerformed
		// TODO add your handling code here:
		nowyDialog.dispose();
	}// GEN-LAST:event_anulujButtonActionPerformed

	private void zapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_zapiszButtonActionPerformed
		// TODO add your handling code here:
		double cena = Double.parseDouble(nowaCenaTextField.getText());
		String nazwa = nowaNazwaTextField.getText();
		Towar t1 = new Towar(nazwa, cena);
		towary.add(t1);

		nowaNazwaTextField.setText("");
		nowaCenaTextField.setText("");
		nowyDialog.dispose();

		System.out.println(towary);
	}// GEN-LAST:event_zapiszButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
		 * feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Magazyn.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Magazyn.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Magazyn.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Magazyn.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Magazyn().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton anulujButton;
	private javax.swing.JTextField cenaTextField;
	private javax.swing.JButton dodajButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel licznikLabel;
	private javax.swing.JButton nastepnyButton;
	private javax.swing.JTextField nazwaTextField;
	private javax.swing.JTextField nowaCenaTextField;
	private javax.swing.JTextField nowaNazwaTextField;
	private javax.swing.JDialog nowyDialog;
	private javax.swing.JLabel nowyLicznikLabel;
	private javax.swing.JButton poprzedniButton;
	private javax.swing.JButton usunButton;
	private javax.swing.JButton zamknijButton;
	private javax.swing.JButton zapiszButton;
	// End of variables declaration//GEN-END:variables
}
